// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWXN3u-xWZF8yIy2ZHUIl_Hp8n19RDKY',
    appId: '1:943852166593:android:1bac92f1e492d99b2e6340',
    messagingSenderId: '943852166593',
    projectId: 'todo-daily-notes',
    storageBucket: 'todo-daily-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALquRxvkehHcW4BE7cOJjNelIkQeYFcSE',
    appId: '1:943852166593:ios:394d10da166f6cc12e6340',
    messagingSenderId: '943852166593',
    projectId: 'todo-daily-notes',
    storageBucket: 'todo-daily-notes.appspot.com',
    androidClientId: '943852166593-3apo9ujm53vpssq1ggvosr1069pdil9e.apps.googleusercontent.com',
    iosClientId: '943852166593-nmh57ggdt04kudot3e2chvt9gvc6m3l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
